import {
  AnchorIcon,
  Bookmark01Icon,
  Briefcase01Icon,
  Bug01Icon,
  CloudIcon,
  CloudServerIcon,
  ComputerIcon,
  CrownIcon,
  Database01Icon,
  FavouriteIcon,
  Flag01Icon,
  FireIcon,
  GemIcon,
  GlobeIcon,
  Home01Icon,
  Key01Icon,
  LockIcon,
  MoonIcon,
  RocketIcon,
  Settings01Icon,
  Shield01Icon,
  SkullIcon,
  StarIcon,
  Sun01Icon,
  Tag01Icon,
  UserIcon,
  ZapIcon,
} from "@hugeicons/core-free-icons";
import type { HugeiconHostIcon } from "./types";

// Curated from @hugeicons/core-free-icons (already a project dependency,
// used elsewhere e.g. src/settings/components/ProviderIcon.tsx) — no new
// icon library. Extending this set is one import + one entry.
export const SYMBOL_ICONS: HugeiconHostIcon[] = [
  { id: "symbol-heart", label: "Heart", category: "symbol", kind: "hugeicon", icon: FavouriteIcon },
  { id: "symbol-star", label: "Star", category: "symbol", kind: "hugeicon", icon: StarIcon },
  { id: "symbol-fire", label: "Fire", category: "symbol", kind: "hugeicon", icon: FireIcon, keywords: ["hot"] },
  { id: "symbol-zap", label: "Bolt", category: "symbol", kind: "hugeicon", icon: ZapIcon, keywords: ["lightning"] },
  { id: "symbol-rocket", label: "Rocket", category: "symbol", kind: "hugeicon", icon: RocketIcon },
  { id: "symbol-lock", label: "Lock", category: "symbol", kind: "hugeicon", icon: LockIcon },
  { id: "symbol-key", label: "Key", category: "symbol", kind: "hugeicon", icon: Key01Icon },
  { id: "symbol-shield", label: "Shield", category: "symbol", kind: "hugeicon", icon: Shield01Icon, keywords: ["security"] },
  { id: "symbol-database", label: "Database", category: "symbol", kind: "hugeicon", icon: Database01Icon, keywords: ["db"] },
  { id: "symbol-cloud", label: "Cloud", category: "symbol", kind: "hugeicon", icon: CloudIcon },
  { id: "symbol-cloud-server", label: "Cloud Server", category: "symbol", kind: "hugeicon", icon: CloudServerIcon, keywords: ["server"] },
  { id: "symbol-computer", label: "Computer", category: "symbol", kind: "hugeicon", icon: ComputerIcon, keywords: ["desktop", "pc"] },
  { id: "symbol-globe", label: "Globe", category: "symbol", kind: "hugeicon", icon: GlobeIcon, keywords: ["network"] },
  { id: "symbol-settings", label: "Settings", category: "symbol", kind: "hugeicon", icon: Settings01Icon, keywords: ["gear"] },
  { id: "symbol-home", label: "Home", category: "symbol", kind: "hugeicon", icon: Home01Icon },
  { id: "symbol-tag", label: "Tag", category: "symbol", kind: "hugeicon", icon: Tag01Icon, keywords: ["label"] },
  { id: "symbol-flag", label: "Flag", category: "symbol", kind: "hugeicon", icon: Flag01Icon },
  { id: "symbol-bookmark", label: "Bookmark", category: "symbol", kind: "hugeicon", icon: Bookmark01Icon },
  { id: "symbol-user", label: "User", category: "symbol", kind: "hugeicon", icon: UserIcon, keywords: ["person"] },
  { id: "symbol-anchor", label: "Anchor", category: "symbol", kind: "hugeicon", icon: AnchorIcon },
  { id: "symbol-crown", label: "Crown", category: "symbol", kind: "hugeicon", icon: CrownIcon },
  { id: "symbol-gem", label: "Gem", category: "symbol", kind: "hugeicon", icon: GemIcon },
  { id: "symbol-skull", label: "Skull", category: "symbol", kind: "hugeicon", icon: SkullIcon },
  { id: "symbol-moon", label: "Moon", category: "symbol", kind: "hugeicon", icon: MoonIcon },
  { id: "symbol-sun", label: "Sun", category: "symbol", kind: "hugeicon", icon: Sun01Icon },
  { id: "symbol-bug", label: "Bug", category: "symbol", kind: "hugeicon", icon: Bug01Icon },
  { id: "symbol-briefcase", label: "Briefcase", category: "symbol", kind: "hugeicon", icon: Briefcase01Icon, keywords: ["work"] },
];
