pub mod credentials;
pub mod errors;
#[cfg(target_os = "macos")]
pub mod dock_menu;
pub mod fs;
pub mod git;
pub mod hosts;
pub mod mcp;
pub mod pty;
pub mod secrets;
pub mod sftp;
pub mod shell;
pub mod snippets;
pub mod ssh;
pub mod themes;
pub mod backgrounds;
pub mod scrollback;
